name: CI Pipeline

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build Docker images
        run: docker-compose build

      - name: Start Docker containers
        run: docker-compose up -d

      - name: Update Composer
        run: docker-compose run app composer self-update

      - name: Run Migration
        run: docker-compose run app php artisan migrate --database=mysql_testing

      - name: Run Seeder
        run: docker-compose run app php artisan db:seed --class=DummyContentSeeder --database=mysql_testing

      - name: Run Test
        run: docker-compose run app php vendor/bin/phpunit

      - name: Clean up Docker
        run: docker-compose down -v
        
        
